spring.application.name=Pc2

# Definimos los nombres de las variables que Render va a rellenar
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

# Ejecutar data.sql siempre
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
